### ISSUE TITLE
Great contribution but I'm unable to make it work with Native in Reaper

### ISSUE THREAD

**Issue by BobPaulCL** [ryankeegan/Simple-MIDI-Translator#1]
Hey Ryankeegan, first of all, thanks for this MIDI translator, it's great you made this considering that in almost one year, Meloaudio didn't do anything to add snapshots changes for native. I'm facing the problem that I don't know exactly which input to choose, Is it the TSMIDI2.0, #2? Same thing with the output, Is the Loop MIDI Port (External MIDI Port) the right one to choose? On the other hand, which MODE in Meloaudio MIDI Commander to choose? Sorry if these questions sound noob for you, but the fact is that I'm a total noob in MIDI, just learning about it. Thanks in advance for your help and again, congratulations for this development!
Details on my issue, the received and sent messages are shown as the same I sent form the MIDI Commander, as shown in the image below. Any help would be really appreciated!!!
![image](https://user-images.githubusercontent.com/69880680/90697286-0ce5cc80-e24c-11ea-8a43-e548755017e9.png)

BR,
Bob Paul
Helix Native and MIDI Commander user

**Comment by ryankeegan** [comment]
Hey Bob,

No worries, I had to do some trial and error to get it working on my setup as well. Luckily I am also using Reaper so I should be able to give you some pointers there if need be.

For selecting the input and output, I always select TSMIDI2.0 without a device description as my input and loopMIDI Port "External MIDI Port" for the output. Attached is a screenshot of my available devices. I always select option 1 for input and option 6 for output.

![image](https://user-images.githubusercontent.com/4945314/90716041-c8b0f700-e260-11ea-8300-e33163cecfb4.png)

As for the mode, the preset I provided was intended for a custom mode. With 1-4/E being mapped to CC instructions that would be used to toggle effects and A-D being mapped to PC instructions that would switch snapshots. I have since switched to using the PC-8X or "all PC" mode which maps everything to PC instructions. I did this because I really only found myself switching presets. Regardless of which you choose, the incoming instructions should really start at 0 not 1:

> 192,0|176,69,0
192,1|176,69,1
192,2|176,69,2
192,3|176,69,3
192,4|176,69,4
192,5|176,69,5
192,6|176,69,6
192,7|176,69,7

I will update the release to reflect this.

And lastly, for configuring Reaper. Are you familiar with routing? The way I have it setup, I have a separate track for loopMIDI. I arm the track for recording, then route the output to the track I keep Helix on. If you'd like, I can provide a 'template' project I use for convenience.

**Comment by BobPaulCL** [comment]
Ryan, Thanks for taking the time to answer and to explain me this.

Great to know that you're a Reaper user too.

I'm very familiar using Reaper and MIDI controls with automation or with
external MIDI devices, I do the same, a second track dedicated for MIDI
control the first one containing the guitar signal.

I'll try this ASAP and let you know how it goes, my work day is going to
start in a few minutes, so I'll have to try this in a break during the day.

Thanks again for this program, and I absolutely share the rant about
Meloaudio and Line6 for "making this possible", LOL.

Have a great day and keep rockin'!!!


Roberto P. Espinoza P.

**Comment by BobPaulCL** [comment]
Hi Ryan, still facing the same issue, the sent and received messages are the same, no change at all, tried it following your instructions selecting the right devices, as shown here:
![image](https://user-images.githubusercontent.com/69880680/90799730-a612f280-e2e1-11ea-8c12-cf0be6d9cb50.png)

Te LoopMIDI shows value changes in the total data field and in the troughput/sec, too, as shown below:
![image](https://user-images.githubusercontent.com/69880680/90799799-bc20b300-e2e1-11ea-8e15-6d48234e9c39.png)

I was using the PC-8x preset in the MIDI Commander.

Do you think that my PC regional settings (Chile) may be affecting the code you programmed? Just a supposition.

Thanks again!

**Comment by ryankeegan** [comment]
Hey Bob,

I just noticed that you're on a different MIDI channel. In your first screenshot it was channel 9 and in your latest it is channel 10. This will affect the default mappings as it assumes the incoming instructions are on channel 1 (192 is channel 1 for PC instructions). Did you change modes on the MIDI Commander controller by chance? That may have been responsible for the channel change.

Regardless, you can use [this table](https://www.midi.org/specifications-old/item/table-2-expanded-messages-list-status-bytes) for reference. Search for '192' then look to the next column over. That should help you figure out what to change the mapping to. So the first mapping will become

> 201,0|176,69,0

assuming you continue using channel 10. You'd just replace all of the '192's in the other mappings with '201'.

You may want to ensure that the channel isn't changing every time you restart your MIDI controller. If it's not then you could just change the mappings to expect input on channel 10.

**Comment by BobPaulCL** [comment]
Hey Ryan, good point, actually, I've changed channels in the settings menu of the MIDI Commander, yesterday, while I was trying to make the program to work. I'll correct this immediately by changing to 201 in the mappings file and come back to you, thanks!!!

**Comment by BobPaulCL** [comment]
IT WORKS, BUDDY, IT'S ALIVE!!!!!
![Its-Alive](https://user-images.githubusercontent.com/69880680/90819238-b89b2500-e2fd-11ea-90dc-c444b23cb3e3.gif)

Great job and thanks for the guidance and patience, really appreciate it!

Do you mind if I share your program in a MIDI group in Facebook? All the credits for you, obviously.

Greetings.

**Comment by BobPaulCL** [comment]
What about preset changes within the same bank/setlist? Have you managed to make it work for this purpose? It's kind of confusing for me yet, considering that presets changes have more MIDI information than snapshots.

![image](https://user-images.githubusercontent.com/69880680/90821006-3e1fd480-e300-11ea-921f-f72b0902e64b.png)


Thanks again, Ryan!

**Comment by ryankeegan** [comment]
Awesome! And yes, absolutely feel free to share the program just ensure you include the license.

As for preset switching, if my memory serves me right it is a plugin limitation. I believe VST3 can't receive PC events which is required to switch presets. Unfortunately Line 6 hasn't made any of the actions rebindable (hence needing this program to enable snapshot switching). However, I do believe it is supported with the AU version of Helix Native but that only works on macOS. Here's [a thread](https://www.thegearpage.net/board/index.php?threads/helix-native-with-midi.2071780/) I found discussing the issue.

**Comment by BobPaulCL** [comment]
Thanks, I'll share the project link in Github and my personal satisfactory results, that's all.

Yes, you're right, I remeber that the preset changes are not available in the VST3 plugin. I hope Line6 will make an update soon considering this functionality. The AU version, you're right; but in my case, I'm a Windows guy XD.

I'll check the thread out.

All the best for you and i'll follow this project for further improvements and if I can help in anything, just let me know!
